/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#define PERIPH_BASE (0x40000000UL)

#define AHB1PERIPH_OFFSET (0x00020000UL)
#define AHB1PERIPH_BASE (PERIPH_BASE + AHB1PERIPH_OFFSET)

#define AHB2PERIPH_OFFSET (0x02020000UL)
#define AHB2PERIPH_BASE (PERIPH_BASE + AHB2PERIPH_OFFSET)

#define GPIOC_OFFSET (0x0800UL)
#define GPIOC_BASE (AHB2PERIPH_BASE + GPIOC_OFFSET)


#define RCC_OFFSET (0x1000UL)
#define RCC_BASE (AHB1PERIPH_BASE + RCC_OFFSET)

#define AHB2EN_R_OFFSET (0x04CUL)
#define RCC_AHB2EN_R (*(volatile unsigned int *)(RCC_BASE + AHB2EN_R_OFFSET))

#define MODE_R_OFFSET (0x00UL)

#define GPIOC_MODE_R (*(volatile unsigned int *)(GPIOC_BASE + MODE_R_OFFSET))

#define OD_R_OFFSET (0x14UL)

#define GPIOC_OD_R (*(volatile unsigned int *)(GPIOC_BASE + OD_R_OFFSET))

#define GPIOCEN (1U<<2)

#define PIN5 (1U<<7)

#define LED_PIN PIN5

// 17: Start of main function
int main(void)
{

	// 18: Enable clock access to GPIOC
	RCC_AHB2EN_R |= GPIOCEN;

	// 19: Set bit 14 to 1
	GPIOC_MODE_R |= (1U<<14);

	// 20: Set bit 15 to 0
	GPIOC_MODE_R &= ~(1U<<15);

	// 21: Start of infinite loop
	while(1)
	{
		 // 22: Set PC7(LED_PIN) high
		 GPIOC_OD_R |= LED_PIN;
		 for(int i = 0; i < 300000; i++){}
		 // 22: Set PC7(LED_PIN) low
		 GPIOC_OD_R &= ~(LED_PIN);
		 for(int i = 0; i < 100000; i++){}
	}

}
